- name: "update apt packages."
  become: true
  apt:
    update_cache: yes
    state: latest

- name: "upgrade packages"
  become: true
  apt:
    state: present
    upgrade: yes

- name: "Install Node.js 13"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install --global n
    sudo n 13.8.0

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: Creates directory
#   file:
#     path: ~/web
#     state: directory

# - name: Copy index test page
#   template:
#     src: "files/index.js"
#     dest: "~/web/index.js"

# - name: Executing node
#   shell: |
#     pm2 start ~/web/index.js -f