---
  - name: "install dependencies."
    become: true
    apt:
      name: "tar"
      state: latest
      update_cache: yes

  - name: "copy tar file "
    become: true
    copy:
      #src: /root/project/backend/dist
      src: /root/project/artifact.tar.gz
      #src: /root/project/
      dest: /home/ubuntu/

  - name: "Untar backend folder"
    become: true
    shell: |
      cd /home/ubuntu/
      tar -xzvf artifact.tar.gz
      ls -lha
  - name: Install Node modules
    become: true
    shell: |
      cd /home/ubuntu/backend
      npm i
  - name: Building backend
    become: true
    shell: |
      cd /home/ubuntu/backend
      npm run build
  - name: Start pm2 service
    become: true
    shell: |
      cd /home/ubuntu/backend
      pm2 start npm --name backend -- start