---
  - name: "install dependencies."
    become: true
    apt:
      name: "tar"
      state: latest
      update_cache: yes

  - name: "Create backend folder"
    become: true
    shell: |
      mkdir -p ~/backend-app
      

  - name: "copy tar file "
    become: true
    copy:
      #src: /root/project/backend/dist
      src: /root/project/artifact.tar.gz
      #src: /root/project/
      dest: ~/backend-app/artifact.tar.gz

  - name: "Untar backend folder"
    become: true
    shell: |
      cd ~/backend-app
      tar -xzvf artifact.tar.gz
      ls -la

  - name: "Unarchive backend files to ec2"
    ansible.builtin.unarchive:
      src: /root/project/artifact.tar.gz
      dest: ~/backend-app
      

  - name: "Installing Node Dependencies"
    shell: |
      cd ~/backend-app
      npm i

  - name: "Executing Node app with PM2"
    shell: |
      cd ~/backend-app/dist
      sudo pm2 stop default
      sudo pm2 start main.js
    register: execute_node

  - name: print message
    debug:
      msg: "{{ execute_node.stdout_lines }}"

  - name: "Configure pm2 to start as service"
    shell: |
      sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
      pm2 save