---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes
      state: present

  - name: "upgrade packages"
    become: yes
    apt:
      state: present
      upgrade: yes

  - name: "install nodejs "
    become: yes
    apt:
      name: nodejs
      state: present
      update_cache: yes

  - name: "install npm"
    become: yes
    apt:
      name: npm
      state: present
      update_cache: yes

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present